package com.mycompany.oodms.admin.GUI;

import com.mycompany.oodms.OODMS;
import com.mycompany.oodms.user.GUI.HomePage;

public class AdminPanelForm extends javax.swing.JPanel {

    /**
     * Creates new form AdminPanelForm
     */
    public AdminPanelForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLab = new javax.swing.JLabel();
        ManageAccBut = new javax.swing.JButton();
        AddDataBut = new javax.swing.JButton();
        ManageProBut = new javax.swing.JButton();
        LogoutBut = new javax.swing.JButton();
        ExitBut = new javax.swing.JButton();
        ManageCatBut = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 300));
        setRequestFocusEnabled(false);

        TitleLab.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        TitleLab.setText("Admin Panel");

        ManageAccBut.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        ManageAccBut.setText("Account Management");
        ManageAccBut.setFocusable(false);
        ManageAccBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageAccButActionPerformed(evt);
            }
        });

        AddDataBut.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        AddDataBut.setText("Add Product");
        AddDataBut.setFocusable(false);
        AddDataBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDataButActionPerformed(evt);
            }
        });

        ManageProBut.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        ManageProBut.setText("Product Management");
        ManageProBut.setFocusable(false);
        ManageProBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageProButActionPerformed(evt);
            }
        });

        LogoutBut.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        LogoutBut.setText("Logout");
        LogoutBut.setFocusable(false);
        LogoutBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButActionPerformed(evt);
            }
        });

        ExitBut.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        ExitBut.setText("Exit");
        ExitBut.setFocusable(false);
        ExitBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButActionPerformed(evt);
            }
        });

        ManageCatBut.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        ManageCatBut.setText("Category Management");
        ManageCatBut.setFocusable(false);
        ManageCatBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageCatButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(TitleLab))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(464, 464, 464)
                        .addComponent(LogoutBut)
                        .addGap(6, 6, 6)
                        .addComponent(ExitBut))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ManageAccBut, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(ManageProBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ManageCatBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddDataBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(TitleLab)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddDataBut)
                    .addComponent(ManageAccBut))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ManageProBut)
                    .addComponent(ManageCatBut))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoutBut)
                    .addComponent(ExitBut)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ManageAccButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageAccButActionPerformed
        OODMS.frame.refresh(new AccountManagementPage());
    }//GEN-LAST:event_ManageAccButActionPerformed

    private void AddDataButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDataButActionPerformed
        OODMS.frame.refresh(new AddProductPage());
    }//GEN-LAST:event_AddDataButActionPerformed

    private void ManageProButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageProButActionPerformed
        OODMS.frame.refresh(new AdminProductPage());
    }//GEN-LAST:event_ManageProButActionPerformed

    private void LogoutButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButActionPerformed
        OODMS.currentUser = null;
        OODMS.frame.refresh(new HomePage());
    }//GEN-LAST:event_LogoutButActionPerformed

    private void ExitButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButActionPerformed
        OODMS.frame.dispose();
    }//GEN-LAST:event_ExitButActionPerformed

    private void ManageCatButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageCatButActionPerformed
        OODMS.frame.refresh(new CategoryManagementPage());
    }//GEN-LAST:event_ManageCatButActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDataBut;
    private javax.swing.JButton ExitBut;
    private javax.swing.JButton LogoutBut;
    private javax.swing.JButton ManageAccBut;
    private javax.swing.JButton ManageCatBut;
    private javax.swing.JButton ManageProBut;
    private javax.swing.JLabel TitleLab;
    // End of variables declaration//GEN-END:variables
}
