package com.mycompany.oodms.admin.GUI;

import com.mycompany.oodms.OODMS;
import com.mycompany.oodms.user.GUI.HomePage;

public class AdminPanelForm extends javax.swing.JPanel {

    /**
     * Creates new form AdminPanelForm
     */
    public AdminPanelForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLab = new javax.swing.JLabel();
        ManageAccBut = new javax.swing.JButton();
        AddDataBut = new javax.swing.JButton();
        ManageProBut = new javax.swing.JButton();
        LogoutBut = new javax.swing.JButton();
        ExitBut = new javax.swing.JButton();
        ManageCatBut = new javax.swing.JButton();
        OrderDeliManBut = new javax.swing.JButton();
        ViewReportBut = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(675, 380));
        setPreferredSize(new java.awt.Dimension(675, 380));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleLab.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        TitleLab.setText("Admin Panel");
        add(TitleLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        ManageAccBut.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        ManageAccBut.setText("Account Management");
        ManageAccBut.setFocusable(false);
        ManageAccBut.setMargin(new java.awt.Insets(4, 14, 3, 14));
        ManageAccBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageAccButActionPerformed(evt);
            }
        });
        add(ManageAccBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 250, 40));

        AddDataBut.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        AddDataBut.setText("Add Product");
        AddDataBut.setFocusable(false);
        AddDataBut.setMargin(new java.awt.Insets(4, 14, 3, 14));
        AddDataBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDataButActionPerformed(evt);
            }
        });
        add(AddDataBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 250, 40));

        ManageProBut.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        ManageProBut.setText("Product Management");
        ManageProBut.setFocusable(false);
        ManageProBut.setMargin(new java.awt.Insets(4, 14, 3, 14));
        ManageProBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageProButActionPerformed(evt);
            }
        });
        add(ManageProBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 250, 40));

        LogoutBut.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        LogoutBut.setText("Logout");
        LogoutBut.setFocusable(false);
        LogoutBut.setMargin(new java.awt.Insets(4, 14, 3, 14));
        LogoutBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButActionPerformed(evt);
            }
        });
        add(LogoutBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 90, 30));

        ExitBut.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        ExitBut.setText("Exit");
        ExitBut.setFocusable(false);
        ExitBut.setMargin(new java.awt.Insets(4, 14, 3, 14));
        ExitBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButActionPerformed(evt);
            }
        });
        add(ExitBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 90, 30));

        ManageCatBut.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        ManageCatBut.setText("Category Management");
        ManageCatBut.setFocusable(false);
        ManageCatBut.setMargin(new java.awt.Insets(4, 14, 3, 14));
        ManageCatBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageCatButActionPerformed(evt);
            }
        });
        add(ManageCatBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 250, 40));

        OrderDeliManBut.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        OrderDeliManBut.setText("Order Delivery Management");
        OrderDeliManBut.setFocusable(false);
        OrderDeliManBut.setMargin(new java.awt.Insets(4, 14, 3, 14));
        OrderDeliManBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderDeliManButActionPerformed(evt);
            }
        });
        add(OrderDeliManBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 250, 40));

        ViewReportBut.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        ViewReportBut.setText("View Report");
        ViewReportBut.setFocusable(false);
        ViewReportBut.setMargin(new java.awt.Insets(4, 14, 3, 14));
        ViewReportBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewReportButActionPerformed(evt);
            }
        });
        add(ViewReportBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 250, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void ManageAccButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageAccButActionPerformed
        OODMS.frame.refresh(new AccountManagementPage());
    }//GEN-LAST:event_ManageAccButActionPerformed

    private void AddDataButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDataButActionPerformed
        OODMS.frame.refresh(new AddProductPage());
    }//GEN-LAST:event_AddDataButActionPerformed

    private void ManageProButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageProButActionPerformed
        OODMS.frame.refresh(new AdminProductPage());
    }//GEN-LAST:event_ManageProButActionPerformed

    private void LogoutButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButActionPerformed
        OODMS.currentUser = null;
        OODMS.frame.refresh(new HomePage());
    }//GEN-LAST:event_LogoutButActionPerformed

    private void ExitButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButActionPerformed
        OODMS.frame.dispose();
    }//GEN-LAST:event_ExitButActionPerformed

    private void ManageCatButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageCatButActionPerformed
        OODMS.frame.refresh(new CategoryManagementPage());
    }//GEN-LAST:event_ManageCatButActionPerformed

    private void OrderDeliManButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderDeliManButActionPerformed
        OODMS.frame.refresh(new OrderDeliveryManagementPage());
    }//GEN-LAST:event_OrderDeliManButActionPerformed

    private void ViewReportButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewReportButActionPerformed
        OODMS.frame.refresh(new ViewReportPage());
    }//GEN-LAST:event_ViewReportButActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDataBut;
    private javax.swing.JButton ExitBut;
    private javax.swing.JButton LogoutBut;
    private javax.swing.JButton ManageAccBut;
    private javax.swing.JButton ManageCatBut;
    private javax.swing.JButton ManageProBut;
    private javax.swing.JButton OrderDeliManBut;
    private javax.swing.JLabel TitleLab;
    private javax.swing.JButton ViewReportBut;
    // End of variables declaration//GEN-END:variables
}
