package com.mycompany.oodms.admin.GUI;

import com.mycompany.oodms.OODMS;

public class ViewMonthlyReportPage extends javax.swing.JPanel {
    
    
    
    public ViewMonthlyReportPage(String date) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtt = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TotalOrderDeliveredTxt = new javax.swing.JLabel();
        TotalIncomeLab = new javax.swing.JLabel();
        TotalOrderPendingLab = new javax.swing.JLabel();
        TotalProductSoldLab = new javax.swing.JLabel();
        TotalAmountofOrderLab = new javax.swing.JLabel();
        TotalOrderDeliveringLab = new javax.swing.JLabel();
        TotalOrderDeliveredLab = new javax.swing.JLabel();
        TotalIncomeTxt = new javax.swing.JLabel();
        TotalProductSoldTxt = new javax.swing.JLabel();
        TotalAmountofOrderTxt = new javax.swing.JLabel();
        TotalOrderPendingTxt = new javax.swing.JLabel();
        TotalOrderDeliveringTxt = new javax.swing.JLabel();
        TitleLab = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(600, 380));
        setPreferredSize(new java.awt.Dimension(600, 380));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        backBtt.setText("Back");
        backBtt.setFocusable(false);
        backBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBttActionPerformed(evt);
            }
        });
        add(backBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TotalOrderDeliveredTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TotalOrderDeliveredTxt.setText("0");
        jPanel1.add(TotalOrderDeliveredTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 180, 30));

        TotalIncomeLab.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TotalIncomeLab.setText("Total Income:");
        jPanel1.add(TotalIncomeLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 30));

        TotalOrderPendingLab.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TotalOrderPendingLab.setText("Total Order Pending:");
        jPanel1.add(TotalOrderPendingLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 200, 30));

        TotalProductSoldLab.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TotalProductSoldLab.setText("Total Product Sold:");
        jPanel1.add(TotalProductSoldLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, 30));

        TotalAmountofOrderLab.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TotalAmountofOrderLab.setText("Total Amount of Order:");
        jPanel1.add(TotalAmountofOrderLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, 30));

        TotalOrderDeliveringLab.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TotalOrderDeliveringLab.setText("Total Order Delivering:");
        jPanel1.add(TotalOrderDeliveringLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 200, 30));

        TotalOrderDeliveredLab.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TotalOrderDeliveredLab.setText("Total Order Delivered:");
        jPanel1.add(TotalOrderDeliveredLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 200, 30));

        TotalIncomeTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TotalIncomeTxt.setText("RM 00.00");
        jPanel1.add(TotalIncomeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 180, 30));

        TotalProductSoldTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TotalProductSoldTxt.setText("0");
        jPanel1.add(TotalProductSoldTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 180, 30));

        TotalAmountofOrderTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TotalAmountofOrderTxt.setText("0");
        jPanel1.add(TotalAmountofOrderTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 180, 30));

        TotalOrderPendingTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TotalOrderPendingTxt.setText("0");
        jPanel1.add(TotalOrderPendingTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 180, 30));

        TotalOrderDeliveringTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TotalOrderDeliveringTxt.setText("0");
        jPanel1.add(TotalOrderDeliveringTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 180, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 480, 260));

        TitleLab.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        TitleLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLab.setText("View (Month) Report");
        add(TitleLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 400, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBttActionPerformed
        OODMS.frame.refresh(new ViewReportPage());
    }//GEN-LAST:event_backBttActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitleLab;
    private javax.swing.JLabel TotalAmountofOrderLab;
    private javax.swing.JLabel TotalAmountofOrderTxt;
    private javax.swing.JLabel TotalIncomeLab;
    private javax.swing.JLabel TotalIncomeTxt;
    private javax.swing.JLabel TotalOrderDeliveredLab;
    private javax.swing.JLabel TotalOrderDeliveredTxt;
    private javax.swing.JLabel TotalOrderDeliveringLab;
    private javax.swing.JLabel TotalOrderDeliveringTxt;
    private javax.swing.JLabel TotalOrderPendingLab;
    private javax.swing.JLabel TotalOrderPendingTxt;
    private javax.swing.JLabel TotalProductSoldLab;
    private javax.swing.JLabel TotalProductSoldTxt;
    private javax.swing.JButton backBtt;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
