/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.oodms.user.GUI;

/**
 *
 * @author Wong Chi Jian
 */
public class ProductPage extends javax.swing.JPanel {

    /**
     * Creates new form ProductPage
     */
    public ProductPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addToCartBtt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        categoryTable = new javax.swing.JTable();
        JScrollPane2 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        titleLb = new javax.swing.JLabel();
        despLb = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addToCartBtt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addToCartBtt.setText("Add To Cart");
        addToCartBtt.setFocusable(false);
        addToCartBtt.setPreferredSize(new java.awt.Dimension(200, 50));
        addToCartBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartBttActionPerformed(evt);
            }
        });
        add(addToCartBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 730, -1, 40));

        categoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        categoryTable.setColumnSelectionAllowed(true);
        categoryTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(categoryTable);
        categoryTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (categoryTable.getColumnModel().getColumnCount() > 0) {
            categoryTable.getColumnModel().getColumn(0).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 180, 690));

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price", "Stock Avaiable"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productTable.setColumnSelectionAllowed(true);
        productTable.getTableHeader().setReorderingAllowed(false);
        JScrollPane2.setViewportView(productTable);
        productTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (productTable.getColumnModel().getColumnCount() > 0) {
            productTable.getColumnModel().getColumn(0).setResizable(false);
            productTable.getColumnModel().getColumn(1).setResizable(false);
            productTable.getColumnModel().getColumn(2).setResizable(false);
            productTable.getColumnModel().getColumn(3).setResizable(false);
        }

        add(JScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 560, 690));

        titleLb.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        titleLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLb.setText("Product");
        add(titleLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        despLb.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        despLb.setOpaque(true);
        add(despLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 380, 630));
    }// </editor-fold>//GEN-END:initComponents

    private void addToCartBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartBttActionPerformed
        
    }//GEN-LAST:event_addToCartBttActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane2;
    private javax.swing.JButton addToCartBtt;
    private javax.swing.JTable categoryTable;
    private javax.swing.JLabel despLb;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loginBtt;
    private javax.swing.JButton loginBtt1;
    private javax.swing.JTable productTable;
    private javax.swing.JLabel titleLb;
    // End of variables declaration//GEN-END:variables
}
