/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.oodms.user.GUI;

import com.mycompany.oodms.OODMS;
import com.mycompany.oodms.customer.Customer;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Wong Chi Jian
 */
public class RegisterPage extends javax.swing.JPanel {

    /**
     * Creates new form RegisterPage
     */
    public RegisterPage() {
        initComponents();
        cfPssMsgLb.setVisible(false);
        emailMsgLb.setVisible(false);
        phoneNoMsgLb.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtt = new javax.swing.JButton();
        titleLb = new javax.swing.JLabel();
        registerBtt = new javax.swing.JButton();
        formPn = new javax.swing.JPanel();
        usernameLb = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        pssLb = new javax.swing.JLabel();
        pssField1 = new javax.swing.JPasswordField();
        cfPssLb = new javax.swing.JLabel();
        pssField2 = new javax.swing.JPasswordField();
        emailLb = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        PhoneNoLb = new javax.swing.JLabel();
        phoneNoField = new javax.swing.JTextField();
        usernameMsgLb = new javax.swing.JLabel();
        pssMsgLb = new javax.swing.JLabel();
        cfPssMsgLb = new javax.swing.JLabel();
        emailMsgLb = new javax.swing.JLabel();
        phoneNoMsgLb = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(600, 450));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        backBtt.setText("Back");
        backBtt.setFocusable(false);
        backBtt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backBtt.setInheritsPopupMenu(true);
        backBtt.setMargin(new java.awt.Insets(0, 0, 0, 0));
        backBtt.setPreferredSize(new java.awt.Dimension(200, 50));
        backBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBttActionPerformed(evt);
            }
        });
        add(backBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 30));

        titleLb.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        titleLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLb.setText("Register");
        add(titleLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 240, -1));

        registerBtt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        registerBtt.setText("Register");
        registerBtt.setFocusable(false);
        registerBtt.setPreferredSize(new java.awt.Dimension(200, 50));
        registerBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBttActionPerformed(evt);
            }
        });
        add(registerBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, 40));

        formPn.setBackground(new java.awt.Color(255, 255, 255));
        formPn.setPreferredSize(new java.awt.Dimension(540, 320));
        formPn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameLb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usernameLb.setText("Username:");
        formPn.add(usernameLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 30));

        usernameField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usernameField.setToolTipText("");
        usernameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 2, true));
        formPn.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 340, 30));

        pssLb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pssLb.setText("Password:");
        formPn.add(pssLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 150, 30));

        pssField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 2, true));
        formPn.add(pssField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 340, 30));

        cfPssLb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cfPssLb.setText("Confirm Password:");
        formPn.add(cfPssLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 160, 30));

        pssField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 2, true));
        formPn.add(pssField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 340, 30));

        emailLb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emailLb.setText("Email:");
        formPn.add(emailLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 150, 30));

        emailField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emailField.setToolTipText("");
        emailField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 2, true));
        formPn.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 340, 30));

        PhoneNoLb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PhoneNoLb.setText("Phone Number:");
        formPn.add(PhoneNoLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 150, 30));

        phoneNoField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phoneNoField.setToolTipText("");
        phoneNoField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 2, true));
        formPn.add(phoneNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 340, 30));

        usernameMsgLb.setText("Username must be at least 4 characters");
        formPn.add(usernameMsgLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 340, 20));

        pssMsgLb.setText("Password length must be at least 8");
        formPn.add(pssMsgLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 340, 20));

        cfPssMsgLb.setForeground(java.awt.Color.red);
        cfPssMsgLb.setText("Confirm Password is not same as Password!");
        formPn.add(cfPssMsgLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 340, 20));

        emailMsgLb.setForeground(java.awt.Color.red);
        emailMsgLb.setText("Email is invalid!");
        formPn.add(emailMsgLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 340, 20));

        phoneNoMsgLb.setForeground(java.awt.Color.red);
        phoneNoMsgLb.setText("Phone Number is invalid!");
        formPn.add(phoneNoMsgLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 340, 20));

        add(formPn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 540, 320));
    }// </editor-fold>//GEN-END:initComponents

    private void backBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBttActionPerformed
        OODMS.frame.refresh(new HomePage());
    }//GEN-LAST:event_backBttActionPerformed

    private void registerBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBttActionPerformed
        String username = usernameField.getText();
        String pss1 = new String(pssField1.getPassword());
        String pss2 = new String(pssField2.getPassword());
        String email = emailField.getText();
        String phoneNo = phoneNoField.getText();

        String errMsg = Customer.register(username, pss1, pss2, email, phoneNo);

        resetRegisterFormUI();

        if (errMsg.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Account has successfully created", "Success", JOptionPane.INFORMATION_MESSAGE);
            OODMS.frame.refresh(new HomePage());
            return;
        }

        if (errMsg.contains("Username character less than 4")) {
            usernameMsgLb.setText("Username invalid, username must be at least 4 characters!");
            usernameMsgLb.setForeground(Color.RED);
            usernameField.setBorder(BorderFactory.createLineBorder(Color.RED, 2, true));

        } else if (errMsg.contains("Username taken")) {
            usernameMsgLb.setText("Username has been taken!");
            usernameMsgLb.setForeground(Color.RED);
            usernameField.setBorder(BorderFactory.createLineBorder(Color.RED, 2, true));
        }

        if (errMsg.contains("Password length less than 8")) {
            pssMsgLb.setText("Password invalid, password length must be at least 8!");
            pssMsgLb.setForeground(Color.RED);
            pssField1.setBorder(BorderFactory.createLineBorder(Color.RED, 2, true));

        } else if (errMsg.contains("Password length is not same")) {
            cfPssMsgLb.setVisible(true);
            pssField2.setBorder(BorderFactory.createLineBorder(Color.RED, 2, true));
        }

        if (errMsg.contains("Email is invalid")) {
            emailMsgLb.setVisible(true);
            emailField.setBorder(BorderFactory.createLineBorder(Color.RED, 2, true));
        }

        if (errMsg.contains("Phone number is invalid")) {
            phoneNoMsgLb.setVisible(true);
            phoneNoField.setBorder(BorderFactory.createLineBorder(Color.RED, 2, true));
        }
    }//GEN-LAST:event_registerBttActionPerformed

    private void resetRegisterFormUI() {
        usernameMsgLb.setText("Username must be at least 4 characters");
        usernameMsgLb.setForeground(Color.BLACK);
        usernameField.setBorder(BorderFactory.createLineBorder(new Color(51,153,255), 2, true));

        pssMsgLb.setText("Password length must be at least 8");
        pssMsgLb.setForeground(Color.BLACK);
        pssField1.setBorder(BorderFactory.createLineBorder(new Color(51,153,255), 2, true));

        cfPssMsgLb.setVisible(false);
        pssField2.setBorder(BorderFactory.createLineBorder(new Color(51,153,255), 2, true));

        emailMsgLb.setVisible(false);
        emailField.setBorder(BorderFactory.createLineBorder(new Color(51,153,255), 2, true));

        phoneNoMsgLb.setVisible(false);
        phoneNoField.setBorder(BorderFactory.createLineBorder(new Color(51,153,255), 2, true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PhoneNoLb;
    private javax.swing.JButton backBtt;
    private javax.swing.JLabel cfPssLb;
    private javax.swing.JLabel cfPssMsgLb;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLb;
    private javax.swing.JLabel emailMsgLb;
    private javax.swing.JPanel formPn;
    private javax.swing.JTextField phoneNoField;
    private javax.swing.JLabel phoneNoMsgLb;
    private javax.swing.JPasswordField pssField1;
    private javax.swing.JPasswordField pssField2;
    private javax.swing.JLabel pssLb;
    private javax.swing.JLabel pssMsgLb;
    private javax.swing.JButton registerBtt;
    private javax.swing.JLabel titleLb;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLb;
    private javax.swing.JLabel usernameMsgLb;
    // End of variables declaration//GEN-END:variables
}
