/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.oodms.admin;

import com.mycompany.oodms.OODMS;
import java.awt.Dimension;

/**
 *
 * @author USER
 */
public class AdminPanelForm extends javax.swing.JPanel {

    /**
     * Creates new form AdminPanelForm
     */
    public AdminPanelForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLab = new javax.swing.JLabel();
        CreateAccBut = new javax.swing.JButton();
        AddDataBut = new javax.swing.JButton();
        ViewRecBut = new javax.swing.JButton();
        LogoutBut = new javax.swing.JButton();
        ExitBut = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 300));
        setRequestFocusEnabled(false);

        TitleLab.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        TitleLab.setText("Admin Panel");

        CreateAccBut.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        CreateAccBut.setText("Create Account");
        CreateAccBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccButActionPerformed(evt);
            }
        });

        AddDataBut.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        AddDataBut.setText("Add Data");
        AddDataBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDataButActionPerformed(evt);
            }
        });

        ViewRecBut.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        ViewRecBut.setText("View Records");
        ViewRecBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewRecButActionPerformed(evt);
            }
        });

        LogoutBut.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        LogoutBut.setText("Logout");
        LogoutBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButActionPerformed(evt);
            }
        });

        ExitBut.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        ExitBut.setText("Exit");
        ExitBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(CreateAccBut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(AddDataBut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TitleLab)
                        .addGap(225, 225, 225))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ViewRecBut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(222, 222, 222))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LogoutBut)
                        .addGap(6, 6, 6)
                        .addComponent(ExitBut)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(TitleLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateAccBut)
                    .addComponent(AddDataBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(ViewRecBut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LogoutBut)
                            .addComponent(ExitBut))
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CreateAccButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccButActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CreateAccButActionPerformed

    private void AddDataButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDataButActionPerformed
        // TODO add your handling code here:
        OODMS.frame.refresh(new AddDataForm());
    }//GEN-LAST:event_AddDataButActionPerformed

    private void ViewRecButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewRecButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewRecButActionPerformed

    private void LogoutButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutButActionPerformed

    private void ExitButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDataBut;
    private javax.swing.JButton CreateAccBut;
    private javax.swing.JButton ExitBut;
    private javax.swing.JButton LogoutBut;
    private javax.swing.JLabel TitleLab;
    private javax.swing.JButton ViewRecBut;
    // End of variables declaration//GEN-END:variables
}
