/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.oodms.Component;

/**
 *
 * @author Wong Chi Jian
 */
public class EditNumberForm extends javax.swing.JPanel {

    /**
     * Creates new form EditNumberForm
     */
    public EditNumberForm(String title, String labelName, int quantity) {
        initComponents();
        titleLb.setText(title);
        itemLb.setText(String.format("<html><p style=\"width:158px\">%s</p></html>", labelName));
        numberField.setText(String.valueOf(quantity));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numberField = new com.mycompany.oodms.Component.JNumberField();
        itemLb = new javax.swing.JLabel();
        titleLb = new javax.swing.JLabel();
        itemLb1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(328, 115));
        setPreferredSize(new java.awt.Dimension(328, 115));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(numberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 90, 32));

        itemLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemLb.setText("<html><p style=\"width:158px\">%s</p></html>");
        itemLb.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(itemLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, 60));

        titleLb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLb.setText("Title");
        add(titleLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 210, 30));

        itemLb1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemLb1.setText(":");
        add(itemLb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 10, 30));
    }// </editor-fold>//GEN-END:initComponents
    public Integer getNumber() {
        return numberField.getInteger();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel itemLb;
    private javax.swing.JLabel itemLb1;
    private com.mycompany.oodms.Component.JNumberField numberField;
    private javax.swing.JLabel titleLb;
    // End of variables declaration//GEN-END:variables
}
