/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.oodms.customer.GUI;

import com.mycompany.oodms.OODMS;
import com.mycompany.oodms.customer.Customer;
import com.mycompany.oodms.customer.CustomerDao;
import com.mycompany.oodms.user.User;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Wong Chi Jian
 */
public class CustomerChangePasswordPage extends javax.swing.JPanel {

    private final CustomerDao customerDao;
    /**
     * Creates new form CustomerChangePasswordPage
     */
    public CustomerChangePasswordPage() {
        customerDao = OODMS.getCustomerDao();
        initComponents();
        cfPssMsgLb.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cfPssLb = new javax.swing.JLabel();
        pssLb = new javax.swing.JLabel();
        pssField1 = new javax.swing.JPasswordField();
        pssMsgLb = new javax.swing.JLabel();
        pssField2 = new javax.swing.JPasswordField();
        cfPssMsgLb = new javax.swing.JLabel();
        changePssBtt = new javax.swing.JButton();
        titleLb = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(540, 250));
        setPreferredSize(new java.awt.Dimension(540, 250));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cfPssLb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cfPssLb.setText("Confirm Password:");
        add(cfPssLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 160, 30));

        pssLb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pssLb.setText("Password:");
        add(pssLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, 30));

        pssField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 2, true));
        add(pssField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 340, 30));

        pssMsgLb.setText("Password length must be at least 8");
        add(pssMsgLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 340, 20));

        pssField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 2, true));
        add(pssField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 340, 30));

        cfPssMsgLb.setForeground(java.awt.Color.red);
        cfPssMsgLb.setText("Confirm Password is not same as Password!");
        add(cfPssMsgLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 340, 20));

        changePssBtt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        changePssBtt.setText("Change Password");
        changePssBtt.setFocusable(false);
        changePssBtt.setMargin(new java.awt.Insets(0, 0, 0, 0));
        changePssBtt.setPreferredSize(new java.awt.Dimension(200, 50));
        changePssBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePssBttActionPerformed(evt);
            }
        });
        add(changePssBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 180, 35));

        titleLb.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        titleLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLb.setText("Change Password");
        add(titleLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void changePssBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePssBttActionPerformed
        pssMsgLb.setText("Password length must be at least 8");
        pssMsgLb.setForeground(Color.BLACK);
        pssField1.setBorder(BorderFactory.createLineBorder(new Color(51,153,255), 2, true));

        cfPssMsgLb.setVisible(false);
        pssField2.setBorder(BorderFactory.createLineBorder(new Color(51,153,255), 2, true));

        String pss1 = new String(pssField1.getPassword());
        String pss2 = new String(pssField2.getPassword());

        // validate the password field
        String errMsg = User.validate(pss1,pss2);

        // if no error message after validate, update customer password
        if (errMsg.isEmpty()) {
            Customer customer = (Customer) OODMS.currentUser;
            customer.setPassword(pss1);
            if (customerDao.fileUpdate(customer)) {
                JOptionPane.showMessageDialog(null, "Password successfully change!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "There is an error occur, your password will not be change!", "Failed", JOptionPane.ERROR_MESSAGE);
            }
            OODMS.frame.refresh(new CustomerProfilePage());
            return;
        }
        // show error message in GUI
        if (errMsg.contains("Password length less than 8")) {
            pssMsgLb.setText("Password invalid, password length must be at least 8!");
            pssMsgLb.setForeground(Color.RED);
            pssField1.setBorder(BorderFactory.createLineBorder(Color.RED, 2, true));

        } else if (errMsg.contains("Password length is not same")) {
            cfPssMsgLb.setVisible(true);
            pssField2.setBorder(BorderFactory.createLineBorder(Color.RED, 2, true));
        }
    }//GEN-LAST:event_changePssBttActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cfPssLb;
    private javax.swing.JLabel cfPssMsgLb;
    private javax.swing.JButton changePssBtt;
    private javax.swing.JPasswordField pssField1;
    private javax.swing.JPasswordField pssField2;
    private javax.swing.JLabel pssLb;
    private javax.swing.JLabel pssMsgLb;
    private javax.swing.JLabel titleLb;
    // End of variables declaration//GEN-END:variables
}
