/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.oodms.customer.GUI;

import com.mycompany.oodms.OODMS;
import com.mycompany.oodms.user.GUI.HomePage;
import com.mycompany.oodms.user.GUI.ProductPage;

/**
 *
 * @author Wong Chi Jian
 */
public class CustomerHomePage extends javax.swing.JPanel {

    /**
     * Creates new form CustomerHomePage
     */
    public CustomerHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLb = new javax.swing.JLabel();
        productBtt = new javax.swing.JButton();
        cartBtt = new javax.swing.JButton();
        profileBtt = new javax.swing.JButton();
        exitBtt = new javax.swing.JButton();
        logoutBtt = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(600, 305));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 305));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLb.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        titleLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLb.setText("Welcome to XXX");
        add(titleLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        productBtt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        productBtt.setText("Our Product");
        productBtt.setFocusable(false);
        productBtt.setPreferredSize(new java.awt.Dimension(200, 50));
        productBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productBttActionPerformed(evt);
            }
        });
        add(productBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        cartBtt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cartBtt.setText("Cart");
        cartBtt.setFocusable(false);
        cartBtt.setPreferredSize(new java.awt.Dimension(200, 50));
        cartBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartBttActionPerformed(evt);
            }
        });
        add(cartBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        profileBtt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        profileBtt.setText("Profile/Check Order");
        profileBtt.setFocusable(false);
        profileBtt.setPreferredSize(new java.awt.Dimension(200, 50));
        profileBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBttActionPerformed(evt);
            }
        });
        add(profileBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 250, -1));

        exitBtt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        exitBtt.setText("Exit");
        exitBtt.setFocusable(false);
        exitBtt.setMargin(new java.awt.Insets(0, 0, 0, 0));
        exitBtt.setPreferredSize(new java.awt.Dimension(200, 50));
        exitBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBttActionPerformed(evt);
            }
        });
        add(exitBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 70, 40));

        logoutBtt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        logoutBtt.setText("Logout");
        logoutBtt.setFocusable(false);
        logoutBtt.setMargin(new java.awt.Insets(0, 0, 0, 0));
        logoutBtt.setPreferredSize(new java.awt.Dimension(200, 50));
        logoutBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBttActionPerformed(evt);
            }
        });
        add(logoutBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 90, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void productBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productBttActionPerformed
        OODMS.frame.refresh(new ProductPage());
    }//GEN-LAST:event_productBttActionPerformed

    private void cartBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartBttActionPerformed
        OODMS.frame.refresh(new CustomerCartPage());
    }//GEN-LAST:event_cartBttActionPerformed

    private void profileBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBttActionPerformed
        OODMS.frame.refresh(new CustomerProfilePage());
    }//GEN-LAST:event_profileBttActionPerformed

    private void logoutBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBttActionPerformed
        OODMS.currentUser = null;
        OODMS.frame.refresh(new HomePage());
    }//GEN-LAST:event_logoutBttActionPerformed

    private void exitBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBttActionPerformed
        OODMS.frame.dispose();
    }//GEN-LAST:event_exitBttActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cartBtt;
    private javax.swing.JButton exitBtt;
    private javax.swing.JButton logoutBtt;
    private javax.swing.JButton productBtt;
    private javax.swing.JButton profileBtt;
    private javax.swing.JLabel titleLb;
    // End of variables declaration//GEN-END:variables
}
